discord:
  bot:
    token: 'OTAyOTQ4NzEyNjMwODcwMDE3.YXl2hQ.911ApiycmgkCH3UNmO7v9Wfbb_Q'
  guild:
    guild_id: '901925644689080360'
    common_role_id: '902944237954408448'
  messages:
    successful: 'You successfully verified!'
    no_code: 'Code doesnt exists, try to get new one!'
    banned: 'You was banned on Discord or Minecraft Server!'
minecraft:
  messages:
    successful: '{player}, your verification code - §2{code}§f (Click to copy)'
    unsuccessful: '§4There is a problem, contact the server administrator!'
    havecode: '§cYou already have a code, you can get new code in 1 minute.'