discord:
  bot:
    token: '-'
  guild:
    guild_id: '-'
    common_role_id: '-'
  messages:
    successful: 'You successfully verified!'
    no_code: 'Code doesnt exists, try to get new one!'
    banned: 'You was banned on Discord or Minecraft Server!'
minecraft:
  messages:
    successful: '{player}, your verification code - §2{code}§f (Click to copy)'
    unsuccessful: '§4There is a problem, contact the server administrator!'
    havecode: '§cYou already have a code, you can get new code in 1 minute.'
